#ifndef ERRORS_H__
#define ERRORS_H__

#define ERR_UNDIFINDED_ERR "Err0 Undifinded error."
#define ERR_ACCESS_REDIFINED "Err100 Access redefined."
#define ERR_STATIC_REDIFINED "Err101 Static redifined."
#define ERR_STATEMENT_NOT_ASSIGN "Err200 Statement not assign."
#define ERR_STATEMENT_NOT_VAR "Err201 Statement not var."
#define ERR_VAR_CANNOT_START_WITH_NUMBER "Err300 Variable cannot start with a number."
#define ERR_VAR_NO_TYPE "Err301 Var no type."
#define ERR_VAR_TOO_MANY_WORDS "Err302 Variable too many words."
#define ERR_CONST_MUST_BE_FIRST "Err400 Const must be first."
#define ERR_CONST_NOT_VAR "Err401 Const not var."
#define ERR_CONST_REDIFINED "Err402 Const redifined."
#define ERR_STRUCT_NAME_REDIFINED "Err500 Struct redefined name."
#define ERR_STRUCT_CANNOT_BE_CONST "Err501 Struct cannot be const."
#define ERR_STRUCT_NAME_NOT_FOUND "Err502 Struct name not found."
#define ERR_STRUCT_NAME_TOO_MANY_WORDS "Err503 Struct name too many words."
#define ERR_FIELD_COUNT "Err600 Field count must be 2."
#define ERR_FUNCTION_OR_FIELD_NOT_END "Err700 Function or field not end."
#define ERR_FUNCTION_TOO_MANY_RETURN_TYPES "Err701 Function too many return types."
#define ERR_FUNCTION_TOO_FEW_RETURN_TYPES "Err702 Function too few return types."
#define ERR_FUNCTION_RETURN_REDIFINED "Err703 Function return redifined."
#define ERR_FUNCTION_RETURN_MUST_FIRST "Err704 Function return must first."
#define ERR_FUNCTION_NAME_NOT_FOUND "Err705 Function name not found."
#define ERR_FUNCTION_RETURN_NOT_FOUND "Err706 Function return not found."
#define ERR_FUNCTION_CANT_BE_CONST "Err707 Function cannot be const."
#define ERR_OP_NOT_VALID "Err800 Operator not valid."

#endif