#ifndef RULES_H__
#define RULES_H__

#define RULE_IMPORT_FILE_NAME_LEN    128
#define RULE_IMPORT_FILE_COUNT       128
#define RULE_FUNCTION_NAME_LEN       128
#define RULE_FUNCTION_RETURN_COUNT   8
#define RULE_FUNCTION_PARAM_NAME_LEN 64
#define RULE_FUNCTION_PARAM_COUNT    32
#define RULE_STRUCT_TYPE_NAME_LEN    128
#define RULE_STRUCT_FIELD_NAME_MAX   128
#define RULE_ACCESS_NAME_LEN         12
#define RULE_VAR_NAME_LEN            128

#endif